ports:
  - port: 5173
    onOpen: open-preview

tasks:
  - name: Run dev server
    init: |
      npm install
      gp sync-done install
    command: npm run dev
  - name: Show outdated packages
    init: gp sync-await install
    command: npm outdated
    openMode: split-right

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: prevent-merge-on-error
    addComment: false
    addBadge: false
